### PR TITLE
Fix get id when pass user videos url

### PR DESCRIPTION
**Pull request by Drogbi**
When i passed https://www.youtube.com/user/ThreeDaysGraceVideos/videos' i have got 

`{ id: 'videos', service: 'youtube' }`

Of course 'videos' is not id in this case :) 
I fixed that problem and wrote test for that case. I hope I'll merge or fix this case by yourself implementation because I need this package so much.

Thank you

### CODE REVIEW

**Comment by radiovisual** [comment]
@Drogbi, sorry for the late reply on this. Thanks for the contribution! I will merge and publish now.

**Comment by radiovisual** [comment]
Now available in `v3.1.1`

**Comment by volser** [comment]
@Drogbi @coveralls Need to exclude https://www.youtube.com/user/ThreeDaysGraceVideos (without /videos) as well

**Comment by volser** [comment]
currently it returns `{id: "ThreeDaysGraceVideos", service: "youtube"}`

**Comment by radiovisual** [comment]
> Need to exclude `https://www.youtube.com/user/ThreeDaysGraceVideos`
> currently it returns {id: "ThreeDaysGraceVideos", service: "youtube"}

@volser @Drogbi This issue is being fixed in #22

**Pull request merged**
