### PR TITLE
Add support for youtube live format

### PR DESCRIPTION
**Pull request by micohasanen**
Found a new /live/ format that is not supported and added support: should be pretty self-explanatory!

### CODE REVIEW

**Comment by micohasanen** [comment]
@radiovisual Care to merge?

**Comment by radiovisual** [comment]
Sorry for the late reply! I will take a look now. Thanks for your contribution!

**Review by radiovisual — APPROVED** [review]
Thanks for this! Appreciate the contribution. Adding it to the next release.

**Comment by someguy9** [comment]
Any idea when this will be released?

**Comment by radiovisual** [comment]
@micohasanen @someguy9 Sorry, I forgot to publish this release. But it is done now. So the YouTube `/live` format is now available in `v3.7.0`

**Pull request merged**
